APPLICATION = lora-leaf
BOARD ?= samr34-xpro
RIOTBASE ?= $(CURDIR)/../riot
QUIET ?= 1
DEVELHELP ?= 1

SLEEP_SECONDS ?= 300
VERBOSE_DEBUG ?= 0
ENABLE_WAKEUP_PIN ?= 0

LORA_REGION ?= EU868
USEPKG += semtech-loramac

USEMODULE += fmt
USEMODULE += shell
USEMODULE += xtimer
USEMODULE += sx1276
USEMODULE += periph_flashpage

CFLAGS += -DSLEEP_SECONDS=$(SLEEP_SECONDS)
CFLAGS += -DVERBOSE_DEBUG=$(VERBOSE_DEBUG)
CFLAGS += -DENABLE_WAKEUP_PIN=$(ENABLE_WAKEUP_PIN)
CFLAGS += -DDEVEUI=\"$(DEVEUI)\"
CFLAGS += -DAPPEUI=\"$(APPEUI)\"
CFLAGS += -DAPPKEY=\"$(APPKEY)\"

include $(RIOTBASE)/Makefile.include
